// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpz3tamjWYdoZz-1UPDPoeEQOxbWy0LT4',
    appId: '1:461166582783:web:eb9215ed5a8025bfa425ca',
    messagingSenderId: '461166582783',
    projectId: 'justchat-102b5',
    authDomain: 'justchat-102b5.firebaseapp.com',
    storageBucket: 'justchat-102b5.firebasestorage.app',
    measurementId: 'G-DB297HEJEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMJvwUsHGJUCZMuytF-hj9tE5BmVw8K_g',
    appId: '1:461166582783:android:cd2f575d7abeda3ca425ca',
    messagingSenderId: '461166582783',
    projectId: 'justchat-102b5',
    storageBucket: 'justchat-102b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFjlhzslB1qpPn3HM_fl8W_mRljcEuOXA',
    appId: '1:461166582783:ios:66ec4b811153445ea425ca',
    messagingSenderId: '461166582783',
    projectId: 'justchat-102b5',
    storageBucket: 'justchat-102b5.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFjlhzslB1qpPn3HM_fl8W_mRljcEuOXA',
    appId: '1:461166582783:ios:66ec4b811153445ea425ca',
    messagingSenderId: '461166582783',
    projectId: 'justchat-102b5',
    storageBucket: 'justchat-102b5.firebasestorage.app',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpz3tamjWYdoZz-1UPDPoeEQOxbWy0LT4',
    appId: '1:461166582783:web:b23b6d275a1fb24ca425ca',
    messagingSenderId: '461166582783',
    projectId: 'justchat-102b5',
    authDomain: 'justchat-102b5.firebaseapp.com',
    storageBucket: 'justchat-102b5.firebasestorage.app',
    measurementId: 'G-4JH1MZHNQR',
  );
}
